name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: get version
      uses: notiz-dev/github-action-json-property@release
      id: version
      with: 
          path: 'pbiviz.json'
          prop_path: 'visual.version'
    - run: echo ${{steps.version.outputs.prop}}
    - name: build visual
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - run: npm install powerbi-visuals-tools
    - run: npm run package
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: latest version
        path: |
          dist/multistackedchartsmulticat3A8101158FC14988B45B304F265A2203.${{steps.version.outputs.prop}}.pbiviz
      env:
        CI: true
