name: get latest version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: get version
      uses: notiz-dev/github-action-json-property@release
      id: version
      with: 
          path: 'pbiviz.json'
          prop_path: 'visual.version'
    - run: echo ${{steps.version.outputs.prop}}
      env:
        CI: true
